# Generated by Django 6.1 on 2026-09-02 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PlannedWorkout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "workout_type",
                    models.CharField(
                        choices=[
                            ("run", "Run"),
                            ("walk", "Walk"),
                            ("hike", "Hike"),
                            ("bike", "Bike"),
                            ("swim", "Swim"),
                            ("custom", "Custom"),
                        ],
                        default="run",
                        max_length=10,
                        verbose_name="type of workout",
                    ),
                ),
                ("workout_date", models.DateField(verbose_name="date of the workout")),
                (
                    "total_distance",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total planned distance in kilometers.",
                        max_digits=6,
                        verbose_name="total distance (km)",
                    ),
                ),
                (
                    "warm_up",
                    models.CharField(
                        blank=True,
                        help_text="Warm-up plan (e.g. distance, drills or time).",
                        max_length=200,
                        verbose_name="warm up",
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "planned workout",
                "verbose_name_plural": "planned workouts",
                "ordering": ["workout_date", "-created_at"],
            },
        ),
    ]
