# Generated by Django 6.1 on 2026-09-05 00:24

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WeeklySummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        help_text="The week this summary relates to (e.g. the Monday).",
                        verbose_name="date",
                    ),
                ),
                (
                    "summary",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Summary data as JSON.",
                        verbose_name="summary",
                    ),
                ),
            ],
            options={
                "verbose_name": "weekly summary",
                "verbose_name_plural": "weekly summaries",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="Issue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="A short summary of the issue.",
                        max_length=200,
                        verbose_name="title",
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        help_text="Describe the issue in detail; Markdown is supported.",
                        verbose_name="issue text",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The user who created this issue.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="issues",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
            ],
            options={
                "verbose_name": "issue",
                "verbose_name_plural": "issues",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="Label",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="A short name for the label.",
                        max_length=200,
                        verbose_name="title",
                    ),
                ),
                (
                    "colour",
                    models.CharField(
                        choices=[
                            ("primary", "Blue"),
                            ("secondary", "Grey"),
                            ("success", "Green"),
                            ("danger", "Red"),
                            ("warning", "Yellow"),
                            ("light", "Light Grey"),
                            ("dark", "Black"),
                        ],
                        default="primary",
                        help_text="A Bootstrap badge colour.",
                        max_length=20,
                        verbose_name="colour",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="start date")),
                ("end_date", models.DateField(verbose_name="end date")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The user who created this label.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="labels",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
            ],
            options={
                "verbose_name": "label",
                "verbose_name_plural": "labels",
                "ordering": ["start_date", "title"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField(verbose_name="object id")),
                (
                    "action",
                    models.CharField(
                        choices=[("added", "Added"), ("edited", "Edited")],
                        default="added",
                        help_text="What happened to the linked object.",
                        max_length=10,
                        verbose_name="action",
                    ),
                ),
                (
                    "read",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this notification has been read.",
                        verbose_name="read",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        help_text="The user who performed the action.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifications_acted",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="actor",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                        verbose_name="content type",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        blank=True,
                        help_text="The user this notification is for.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="recipient",
                    ),
                ),
            ],
            options={
                "verbose_name": "notification",
                "verbose_name_plural": "notifications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("coach", "Coach"), ("athlete", "Athlete")],
                        default="athlete",
                        help_text="Whether this user is a coach or an athlete.",
                        max_length=10,
                        verbose_name="role",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "user profile",
                "verbose_name_plural": "user profiles",
            },
        ),
        migrations.CreateModel(
            name="WarmUp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="A short name for the warm-up, e.g. 'Easy jog'.",
                        max_length=200,
                        verbose_name="title",
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        help_text="The warm-up routine or instructions.",
                        verbose_name="warm-up text",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The user who created this warm-up.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="warmups",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
            ],
            options={
                "verbose_name": "warm-up",
                "verbose_name_plural": "warm-ups",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="PlannedWorkout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="",
                        help_text="A short name for the workout, e.g. 'Long run'.",
                        max_length=200,
                        verbose_name="title",
                    ),
                ),
                (
                    "workout_type",
                    models.CharField(
                        choices=[
                            ("run", "Run"),
                            ("walk", "Walk"),
                            ("hike", "Hike"),
                            ("strength", "Strength"),
                            ("recovery", "Recovery"),
                        ],
                        default="run",
                        max_length=10,
                        verbose_name="type of workout",
                    ),
                ),
                ("workout_date", models.DateField(verbose_name="date of the workout")),
                (
                    "total_distance",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Total planned distance in kilometers.",
                        max_digits=6,
                        null=True,
                        verbose_name="total distance (km)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("done", "Done"),
                            ("missed", "Missed"),
                            ("over", "Over"),
                            ("under", "Under"),
                        ],
                        default="",
                        help_text="Whether the workout was done, missed, over or under.",
                        max_length=10,
                        verbose_name="status",
                    ),
                ),
                (
                    "is_race",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this planned workout is a race.",
                        verbose_name="race",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Markdown can be used in this field."
                    ),
                ),
                (
                    "comment_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of comments on this workout.",
                        verbose_name="comment count",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The user who created this planned workout.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="planned_workouts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "warm_up",
                    models.ForeignKey(
                        blank=True,
                        help_text="The warm-up routine for this workout.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="workouts",
                        to="alors.warmup",
                        verbose_name="warm up",
                    ),
                ),
            ],
            options={
                "verbose_name": "planned workout",
                "verbose_name_plural": "planned workouts",
                "ordering": ["workout_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Workout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "workout_date",
                    models.DateTimeField(verbose_name="date of the workout"),
                ),
                (
                    "total_time",
                    models.DurationField(
                        help_text="Total duration, e.g. 00:45:00 (hh:mm:ss).",
                        verbose_name="total time",
                    ),
                ),
                (
                    "workout_type",
                    models.CharField(
                        choices=[
                            ("run", "Run"),
                            ("walk", "Walk"),
                            ("hike", "Hike"),
                            ("strength", "Strength"),
                            ("recovery", "Recovery"),
                        ],
                        max_length=10,
                        verbose_name="type",
                    ),
                ),
                (
                    "total_distance",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Total distance covered in kilometers.",
                        max_digits=6,
                        null=True,
                        verbose_name="total distance (km)",
                    ),
                ),
                (
                    "moving_time",
                    models.DurationField(
                        blank=True,
                        help_text="Time spent moving, e.g. 00:44:30 (hh:mm:ss).",
                        null=True,
                        verbose_name="moving time",
                    ),
                ),
                (
                    "pace",
                    models.DurationField(
                        blank=True,
                        help_text="Average pace, e.g. 00:05:30 (hh:mm:ss) per kilometer.",
                        null=True,
                        verbose_name="pace",
                    ),
                ),
                (
                    "effort",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Rate the effort from 1 (easy) to 10 (all out).",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="effort",
                    ),
                ),
                (
                    "feeling",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Rate how you felt from 1 (poor) to 5 (great).",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="feeling",
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "comment_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of comments on this workout.",
                        verbose_name="comment count",
                    ),
                ),
                (
                    "workout_source",
                    models.CharField(
                        blank=True,
                        help_text="Where this workout came from, e.g. Strava, Garmin, manual.",
                        max_length=200,
                        null=True,
                        unique=True,
                        verbose_name="workout source",
                    ),
                ),
                (
                    "source_url",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="A URL for the original source of this workout.",
                        max_length=500,
                        verbose_name="source url",
                    ),
                ),
                (
                    "workout_data",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Additional workout data, stored as JSON text.",
                        verbose_name="workout data",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The user who recorded this workout.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="workouts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "issues",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Issues related to this workout.",
                        related_name="workouts",
                        to="alors.issue",
                        verbose_name="issues",
                    ),
                ),
            ],
            options={
                "verbose_name": "workout",
                "verbose_name_plural": "workouts",
                "ordering": ["-workout_date"],
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        help_text="Your comment; Markdown is supported.",
                        verbose_name="comment",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The user who wrote this comment.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="comments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "planned_workout",
                    models.ForeignKey(
                        blank=True,
                        help_text="The planned workout this comment is about.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="alors.plannedworkout",
                        verbose_name="planned workout",
                    ),
                ),
                (
                    "workout",
                    models.ForeignKey(
                        blank=True,
                        help_text="The completed workout this comment is about.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="alors.workout",
                        verbose_name="workout",
                    ),
                ),
            ],
            options={
                "verbose_name": "comment",
                "verbose_name_plural": "comments",
                "ordering": ["created_at"],
            },
        ),
    ]
