# Generated by Django 6.1 on 2026-09-02 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alors", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plannedworkout",
            name="warm_up",
            field=models.TextField(
                blank=True,
                help_text="Warm-up plan (e.g. distance, drills or time).",
                verbose_name="warm up",
            ),
        ),
        migrations.AlterField(
            model_name="plannedworkout",
            name="workout_type",
            field=models.CharField(
                choices=[("run", "Run"), ("walk", "Walk"), ("hike", "Hike")],
                default="run",
                max_length=10,
                verbose_name="type of workout",
            ),
        ),
    ]
