# Generated by Django 6.1 on 2026-09-05 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("alors", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="issue",
            name="text",
        ),
    ]
