# Generated by Django 6.1 on 2026-09-02 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alors", "0002_alter_plannedworkout_warm_up_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="plannedworkout",
            name="title",
            field=models.CharField(
                default="",
                help_text="A short name for the workout, e.g. 'Long run'.",
                max_length=200,
                verbose_name="title",
            ),
        ),
        migrations.AlterField(
            model_name="plannedworkout",
            name="workout_type",
            field=models.CharField(
                choices=[
                    ("run", "Run"),
                    ("walk", "Walk"),
                    ("hike", "Hike"),
                    ("race", "Race"),
                ],
                default="run",
                max_length=10,
                verbose_name="type of workout",
            ),
        ),
    ]
