# Generated by Django 6.1 on 2026-09-05 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alors", "0002_remove_issue_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="colour",
            field=models.CharField(
                choices=[
                    ("primary", "Blue"),
                    ("secondary", "Grey"),
                    ("success", "Green"),
                    ("danger", "Red"),
                    ("warning", "Yellow"),
                    ("light", "Light Grey"),
                    ("dark", "Black"),
                ],
                default="primary",
                help_text="A Bootstrap badge colour.",
                max_length=20,
                verbose_name="colour",
            ),
        ),
    ]
