# Generated by Django 6.1 on 2026-09-02 20:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alors", "0003_plannedworkout_title_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="plannedworkout",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="The user who created this planned workout.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="planned_workouts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="created by",
            ),
        ),
    ]
