# Generated by Django 6.1 on 2026-09-05 18:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alors", "0003_issue_colour"),
    ]

    operations = [
        migrations.AddField(
            model_name="workout",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="workout",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
