# Generated by Django 6.1 on 2026-09-06 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alors", "0004_workout_created_at_workout_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="avatar",
            field=models.FileField(
                blank=True,
                help_text="An image shown next to your name.",
                null=True,
                upload_to="avatars/",
                verbose_name="profile image",
            ),
        ),
        migrations.AlterField(
            model_name="plannedworkout",
            name="workout_type",
            field=models.CharField(
                choices=[
                    ("run", "Run"),
                    ("walk", "Walk"),
                    ("hike", "Hike"),
                    ("strength", "Strength"),
                    ("recovery", "Recovery"),
                    ("other", "OTHER"),
                ],
                default="run",
                max_length=10,
                verbose_name="type of workout",
            ),
        ),
        migrations.AlterField(
            model_name="workout",
            name="workout_type",
            field=models.CharField(
                choices=[
                    ("run", "Run"),
                    ("walk", "Walk"),
                    ("hike", "Hike"),
                    ("strength", "Strength"),
                    ("recovery", "Recovery"),
                    ("other", "OTHER"),
                ],
                max_length=10,
                verbose_name="type",
            ),
        ),
    ]
