# Generated by Django 6.1 on 2026-09-02 20:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alors", "0004_plannedworkout_created_by"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WarmUp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="A short name for the warm-up, e.g. 'Easy jog'.",
                        max_length=200,
                        verbose_name="title",
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        help_text="The warm-up routine or instructions.",
                        verbose_name="warm-up text",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The user who created this warm-up.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="warmups",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
            ],
            options={
                "verbose_name": "warm-up",
                "verbose_name_plural": "warm-ups",
                "ordering": ["title"],
            },
        ),
    ]
