# Generated by Django 6.1 on 2026-09-09 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alors", "0005_userprofile_avatar_alter_plannedworkout_workout_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="timezone",
            field=models.CharField(
                default="UTC",
                help_text="Your local timezone, used to show dates and times.",
                max_length=63,
                verbose_name="timezone",
            ),
        ),
        migrations.AlterField(
            model_name="plannedworkout",
            name="workout_type",
            field=models.CharField(
                choices=[
                    ("run", "Run"),
                    ("walk", "Walk"),
                    ("hike", "Hike"),
                    ("strength", "Strength"),
                    ("recovery", "Recovery"),
                    ("other", "Other"),
                ],
                default="run",
                max_length=10,
                verbose_name="type of workout",
            ),
        ),
        migrations.AlterField(
            model_name="workout",
            name="workout_type",
            field=models.CharField(
                choices=[
                    ("run", "Run"),
                    ("walk", "Walk"),
                    ("hike", "Hike"),
                    ("strength", "Strength"),
                    ("recovery", "Recovery"),
                    ("other", "Other"),
                ],
                max_length=10,
                verbose_name="type",
            ),
        ),
    ]
