# Generated by Django 6.1 on 2026-09-18 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alors", "0006_userprofile_timezone_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workout",
            name="elevation_gain",
            field=models.FloatField(
                blank=True,
                help_text="Total elevation gained in meters.",
                null=True,
                verbose_name="elevation gain (m)",
            ),
        ),
        migrations.AddField(
            model_name="workout",
            name="elevation_loss",
            field=models.FloatField(
                blank=True,
                help_text="Total elevation lost in meters.",
                null=True,
                verbose_name="elevation loss (m)",
            ),
        ),
    ]
