# Generated by Django 6.1 on 2026-09-02 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alors", "0006_plannedworkout_warmup_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plannedworkout",
            name="warm_up",
            field=models.ForeignKey(
                blank=True,
                help_text="The warm-up routine for this workout.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="workouts",
                to="alors.warmup",
                verbose_name="warm up",
            ),
        ),
    ]
