# Generated by Django 6.1 on 2026-09-02 21:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alors", "0007_alter_plannedworkout_warm_up"),
    ]

    operations = [
        migrations.CreateModel(
            name="Workout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("workout_date", models.DateField(verbose_name="date of the workout")),
                (
                    "total_time",
                    models.DurationField(
                        help_text="Total duration, e.g. 00:45:00 (hh:mm:ss).",
                        verbose_name="total time",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("run", "Run"),
                            ("walk", "Walk"),
                            ("hike", "Hike"),
                            ("race", "Race"),
                        ],
                        max_length=10,
                        verbose_name="type",
                    ),
                ),
                (
                    "distance",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Distance covered in kilometers.",
                        max_digits=6,
                        null=True,
                        verbose_name="distance (km)",
                    ),
                ),
                (
                    "moving_time",
                    models.DurationField(
                        blank=True,
                        help_text="Time spent moving, e.g. 00:44:30 (hh:mm:ss).",
                        null=True,
                        verbose_name="moving time",
                    ),
                ),
                (
                    "average_speed",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Average speed in kilometers per hour.",
                        max_digits=5,
                        null=True,
                        verbose_name="average speed (km/h)",
                    ),
                ),
                (
                    "effort",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Rate the effort from 1 (easy) to 10 (all out).",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="effort",
                    ),
                ),
                (
                    "feeling",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Rate how you felt from 1 (poor) to 5 (great).",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="feeling",
                    ),
                ),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "workout",
                "verbose_name_plural": "workouts",
                "ordering": ["-workout_date"],
            },
        ),
    ]
