# Generated by Django 6.1 on 2026-09-19 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("alors", "0008_backfill_workout_elevation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plannedworkout",
            name="warm_up",
        ),
    ]
