# Generated by Django 6.1 on 2026-09-02 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alors", "0009_rename_distance_workout_total_distance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workout",
            name="total_distance",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Total distance covered in kilometers.",
                max_digits=6,
                null=True,
                verbose_name="total distance (km)",
            ),
        ),
    ]
