# Generated by Django 6.1 on 2026-09-03 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alors", "0010_alter_workout_total_distance"),
    ]

    operations = [
        migrations.CreateModel(
            name="Issue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="A short summary of the issue.",
                        max_length=200,
                        verbose_name="title",
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        help_text="Describe the issue in detail; Markdown is supported.",
                        verbose_name="issue text",
                    ),
                ),
            ],
            options={
                "verbose_name": "issue",
                "verbose_name_plural": "issues",
                "ordering": ["title"],
            },
        ),
    ]
