# Generated by Django 6.1 on 2026-09-19 00:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alors", "0010_rename_warmup_savedworkout"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="savedworkout",
            options={
                "ordering": ["title"],
                "verbose_name": "saved workout",
                "verbose_name_plural": "saved workouts",
            },
        ),
        migrations.AlterField(
            model_name="savedworkout",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="The user who created this saved workout.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="saved_workouts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="created by",
            ),
        ),
        migrations.AlterField(
            model_name="savedworkout",
            name="text",
            field=models.TextField(
                help_text="The workout or instructions.", verbose_name="text"
            ),
        ),
        migrations.AlterField(
            model_name="savedworkout",
            name="title",
            field=models.CharField(
                help_text="A short name for the saved workout, e.g. 'Easy jog'.",
                max_length=200,
                verbose_name="title",
            ),
        ),
    ]
