# Generated by Django 6.1 on 2026-09-03 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alors", "0011_issue"),
    ]

    operations = [
        migrations.AddField(
            model_name="workout",
            name="issues",
            field=models.ManyToManyField(
                blank=True,
                help_text="Issues related to this workout.",
                related_name="workouts",
                to="alors.issue",
                verbose_name="issues",
            ),
        ),
    ]
