# Generated by Django 6.1 on 2026-09-21 16:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alors", "0011_alter_savedworkout_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="plannedworkout",
            constraint=models.UniqueConstraint(
                fields=("workout_date",),
                name="unique_planned_workout_per_day",
                violation_error_message="There is already a planned workout on that day.",
            ),
        ),
    ]
