# Generated by Django 6.1 on 2026-09-03 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alors", "0012_workout_issues"),
    ]

    operations = [
        migrations.CreateModel(
            name="WeeklySummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        help_text="The week this summary relates to (e.g. the Monday).",
                        verbose_name="date",
                    ),
                ),
                (
                    "summary",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Summary data as JSON.",
                        verbose_name="summary",
                    ),
                ),
            ],
            options={
                "verbose_name": "weekly summary",
                "verbose_name_plural": "weekly summaries",
                "ordering": ["-date"],
            },
        ),
    ]
