# Generated by Django 6.1 on 2026-09-26 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alors", "0012_plannedworkout_unique_planned_workout_per_day"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="send_daily_email",
            field=models.BooleanField(
                default=False,
                help_text="Receive a daily email about your training.",
                verbose_name="send daily email",
            ),
        ),
    ]
