# Generated by Django 6.1 on 2026-09-03 20:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alors", "0013_weeklysummary"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="issue",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="The user who created this issue.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="issues",
                to=settings.AUTH_USER_MODEL,
                verbose_name="created by",
            ),
        ),
        migrations.AddField(
            model_name="issue",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
