# Generated by Django 6.1 on 2026-10-04 22:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alors", "0014_remove_unique_planned_workout_per_day"),
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="label",
            index=models.Index(fields=["start_date"], name="label_start_date_idx"),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["content_type", "object_id"], name="notif_content_object_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["recipient", "read"], name="notif_recipient_read_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(fields=["created_at"], name="notif_created_at_idx"),
        ),
        migrations.AddIndex(
            model_name="plannedworkout",
            index=models.Index(
                fields=["workout_date"], name="planned_workout_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workout",
            index=models.Index(fields=["workout_date"], name="workout_date_idx"),
        ),
        migrations.AddConstraint(
            model_name="weeklysummary",
            constraint=models.UniqueConstraint(
                fields=("date",), name="uniq_weekly_summary_date"
            ),
        ),
    ]
