# Generated by Django 6.1 on 2026-10-06 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alors", "0015_label_label_start_date_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workout",
            name="timezone",
            field=models.CharField(
                blank=True,
                default="",
                help_text="The creator's timezone when this workout was created.",
                max_length=63,
                verbose_name="timezone",
            ),
        ),
        migrations.AddField(
            model_name="workout",
            name="workout_date_for_timezone",
            field=models.DateTimeField(
                blank=True,
                help_text="workout_date converted into the creator's timezone.",
                null=True,
                verbose_name="date of the workout in the local timezone",
            ),
        ),
    ]
