# Generated by Django 6.1 on 2026-10-06 03:23

import pytz
from django.conf import settings
from django.db import migrations


def _resolve_timezone(tzname):
    """The pytz timezone for ``tzname``, or the settings default."""
    try:
        return pytz.timezone(tzname)
    except (pytz.UnknownTimeZoneError, ValueError):
        return pytz.timezone(settings.TIME_ZONE)


def backfill_workout_timezones(apps, schema_editor):
    """Fill the new timezone columns for existing workouts.

    Mirrors ``Workout.save``: the creator's profile timezone is captured (with
    the settings default as a fallback) and ``workout_date`` is stored again as
    a naive wall clock in that timezone. Workouts without a creator keep the
    empty/null defaults.
    """
    Workout = apps.get_model("alors", "Workout")
    UserProfile = apps.get_model("alors", "UserProfile")

    profile_timezones = dict(UserProfile.objects.values_list("user_id", "timezone"))

    updates = []
    for workout in Workout.objects.exclude(created_by=None).iterator():
        tzname = profile_timezones.get(workout.created_by_id) or settings.TIME_ZONE
        user_timezone = _resolve_timezone(tzname)
        workout.timezone = user_timezone.zone
        if workout.workout_date is not None:
            value = workout.workout_date
            if value.tzinfo is None:
                value = value.replace(tzinfo=pytz.utc)
            workout.workout_date_for_timezone = value.astimezone(user_timezone).replace(
                tzinfo=None
            )
        updates.append(workout)

        if len(updates) >= 500:
            Workout.objects.bulk_update(
                updates, ["timezone", "workout_date_for_timezone"]
            )
            updates = []

    if updates:
        Workout.objects.bulk_update(updates, ["timezone", "workout_date_for_timezone"])


def clear_workout_timezones(apps, schema_editor):
    """Undo the backfill by resetting the new columns to their defaults."""
    Workout = apps.get_model("alors", "Workout")
    Workout.objects.update(timezone="", workout_date_for_timezone=None)


class Migration(migrations.Migration):

    dependencies = [
        ("alors", "0016_workout_timezone_workout_workout_date_for_timezone"),
    ]

    operations = [
        migrations.RunPython(backfill_workout_timezones, clear_workout_timezones),
    ]
