# Generated by Django 6.1 on 2026-10-06 03:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alors", "0017_backfill_workout_timezones"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="workout",
            index=models.Index(
                fields=["workout_date_for_timezone"], name="workout_date_tz_idx"
            ),
        ),
    ]
