# Generated by Django 6.1 on 2026-10-06 03:30

import pytz
from django.conf import settings
from django.db import migrations


def _resolve_timezone(tzname):
    """The pytz timezone for ``tzname``, or the settings default."""
    try:
        return pytz.timezone(tzname)
    except (pytz.UnknownTimeZoneError, ValueError):
        return pytz.timezone(settings.TIME_ZONE)


def backfill_workout_default_timezones(apps, schema_editor):
    """Fill the timezone columns for workouts 0017 left empty.

    0017 only handled workouts with a creator. Workouts without one now fall
    back to ``settings.TIME_ZONE`` (matching ``Workout.save``), so their rows
    are filled in here.
    """
    Workout = apps.get_model("alors", "Workout")
    UserProfile = apps.get_model("alors", "UserProfile")

    profile_timezones = dict(UserProfile.objects.values_list("user_id", "timezone"))

    updates = []
    for workout in Workout.objects.filter(timezone="").iterator():
        tzname = profile_timezones.get(workout.created_by_id) or settings.TIME_ZONE
        user_timezone = _resolve_timezone(tzname)
        workout.timezone = user_timezone.zone
        if workout.workout_date is not None:
            value = workout.workout_date
            if value.tzinfo is None:
                value = value.replace(tzinfo=pytz.utc)
            workout.workout_date_for_timezone = (
                value.astimezone(user_timezone).replace(tzinfo=None)
            )
        updates.append(workout)

        if len(updates) >= 500:
            Workout.objects.bulk_update(
                updates, ["timezone", "workout_date_for_timezone"]
            )
            updates = []

    if updates:
        Workout.objects.bulk_update(
            updates, ["timezone", "workout_date_for_timezone"]
        )


class Migration(migrations.Migration):

    dependencies = [
        ("alors", "0018_workout_workout_date_tz_idx"),
    ]

    operations = [
        migrations.RunPython(
            backfill_workout_default_timezones, migrations.RunPython.noop
        ),
    ]
