# Generated by Django 6.1 on 2026-10-08 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alors", "0019_backfill_workout_default_timezones"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="The user who created this.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="created by",
            ),
        ),
        migrations.AlterField(
            model_name="issue",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="The user who created this.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="created by",
            ),
        ),
        migrations.AlterField(
            model_name="label",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="The user who created this.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="created by",
            ),
        ),
        migrations.AlterField(
            model_name="plannedworkout",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="The user who created this.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="created by",
            ),
        ),
        migrations.AlterField(
            model_name="savedworkout",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="The user who created this.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="created by",
            ),
        ),
        migrations.AlterField(
            model_name="workout",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="The user who created this.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="created by",
            ),
        ),
    ]
