# Generated by Django 6.1 on 2026-10-08 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alors", "0020_alter_comment_created_by_alter_issue_created_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="units",
            field=models.CharField(
                choices=[("metric", "Metric (kg)"), ("imperial", "Imperial (lb)")],
                default="imperial",
                help_text="Whether to show weights in metric or imperial units.",
                max_length=10,
                verbose_name="units",
            ),
        ),
    ]
