"""
Django settings for glute project.

Generated by 'django-admin startproject' using Django 4.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

import dj_database_url
import os
import sys
from pathlib import Path
from dotenv import load_dotenv

load_dotenv()
from django.utils.csp import CSP

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

STATIC_DIR = os.getenv("DJANGO_STATIC_DIR", BASE_DIR)
SECRET_KEY = os.getenv(
    "DJANGO_SECRET_KEY",
    "django-insecure-z#vdq369mheu9lxu%ylfcbfvba!!=5jm@^!uekvjy_yof2n752",
)
# Set DJANGO_DEBUG to any string to enable, set to empty to turn off.
DEBUG = False  # not not os.getenv("DJANGO_DEBUG", True)

# Local development mode (DJANGO_DEBUG is set in .env). It drives static-file
# serving and local debug tooling, but never applies to the test suite.
LOCAL_DEBUG = bool(os.getenv("DJANGO_DEBUG", ""))
DEBUG_TOOLBAR = LOCAL_DEBUG and "test" not in sys.argv


def show_debug_toolbar(request):
    """Show the toolbar whenever local debug mode is enabled."""
    return DEBUG_TOOLBAR


ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
    "glute.clearwind.ca",
]
allowed_env = os.getenv("ALLOWED_HOSTS", None)
if allowed_env:
    ALLOWED_HOSTS.append(allowed_env)

CSRF_TRUSTED_ORIGINS = []
trusted_env = os.getenv("CSRF_TRUSTED_ORIGINS", None)
if trusted_env:
    CSRF_TRUSTED_ORIGINS.append(trusted_env)

HOST = os.getenv("HOST", "http://localhost:8000")

# Application definition
SECURE_HSTS_SECONDS = 15768000
SESSION_COOKIE_SECURE = True
SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_SECURE = True
CSRF_COOKIE_HTTPONLY = True

SECURE_CSP = {
    "img-src": ["data:", CSP.SELF, "tile.openstreetmap.org"],
    "frame-src": [CSP.NONE],
}

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "alors",
    "weights",
]

if not DEBUG:
    INSTALLED_APPS.append("django.contrib.staticfiles")

if DEBUG_TOOLBAR:
    INSTALLED_APPS.append("debug_toolbar")

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "alors.middleware.UserTimezoneMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django.middleware.csp.ContentSecurityPolicyMiddleware",
]

if DEBUG_TOOLBAR:
    # As early as possible so the toolbar can instrument every request.
    MIDDLEWARE.insert(0, "debug_toolbar.middleware.DebugToolbarMiddleware")
    INTERNAL_IPS = ["127.0.0.1", "localhost"]
    DEBUG_TOOLBAR_CONFIG = {
        # The default callback requires DEBUG, which this project keeps off.
        "SHOW_TOOLBAR_CALLBACK": "glute.settings.show_debug_toolbar",
    }

ROOT_URLCONF = "glute.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": ["alors/templates", "glute/templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "alors.processors.site.site",
            ],
        },
    },
]

WSGI_APPLICATION = "glute.wsgi.application"
DATABASES = {
    "default": dj_database_url.config(conn_max_age=600, conn_health_checks=True)
}

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

LOGIN_URL = "/"

LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True

# Ugh, need to dive into this, but this was breaking on prod.
USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "static/"

# WhiteNoise caches each static file's metadata until the process restarts.
# Locally (where DJANGO_DEBUG is set in .env) refresh it on every request and
# fall back to Django's staticfiles finders, so CSS/JS edits show up without
# restarting runserver and app static (admin, django-debug-toolbar) is served
# without needing collectstatic.
WHITENOISE_AUTOREFRESH = LOCAL_DEBUG
WHITENOISE_USE_FINDERS = LOCAL_DEBUG

# User-uploaded media (profile avatars, etc.)
MEDIA_URL = "/media/"
MEDIA_ROOT = os.getenv("MEDIA_ROOT", BASE_DIR / "media")

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

INTERVALS_TOKEN = os.getenv("INTERVALS_TOKEN", None)
if not INTERVALS_TOKEN:
    print("Warning: no intervals.icu API Key found.")

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
        "file": {
            "level": "ERROR",
            "class": "logging.FileHandler",
            "filename": "error.log",
        },
    },
    "loggers": {
        "django": {
            "handlers": ["console", "file"],
            "level": "ERROR",
            "propagate": True,
        },
    },
}

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_USE_TLS = True
EMAIL_HOST = "smtp.gmail.com"
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")
EMAIL_PORT = 587
DEFAULT_FROM_EMAIL = "noreply@clearwind.ca"
