# Generated by Django 6.1 on 2026-10-08 15:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WeightsWorkout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The user who created this.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
            ],
            options={
                "verbose_name": "weights workout",
                "verbose_name_plural": "weights workouts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WeightsWorkoutExercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "exercise_id",
                    models.PositiveIntegerField(
                        help_text="The exercise id from weights/fitbod/exercises.json.",
                        verbose_name="Exercise id",
                    ),
                ),
                (
                    "position",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Order of the exercise within the workout.",
                        verbose_name="position",
                    ),
                ),
                (
                    "workout",
                    models.ForeignKey(
                        help_text="The workout this exercise belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exercises",
                        to="weights.weightsworkout",
                        verbose_name="workout",
                    ),
                ),
            ],
            options={
                "verbose_name": "workout exercise",
                "verbose_name_plural": "workout exercises",
                "ordering": ["position", "id"],
            },
        ),
    ]
