# Generated by Django 6.1 on 2026-10-08 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weights", "0002_weightsworkout_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="WeightsWorkoutSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reps",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Repetitions in this set.",
                        null=True,
                        verbose_name="reps",
                    ),
                ),
                (
                    "position",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Order of the set within the exercise.",
                        verbose_name="position",
                    ),
                ),
                (
                    "entry",
                    models.ForeignKey(
                        help_text="The exercise this set belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sets",
                        to="weights.weightsworkoutexercise",
                        verbose_name="exercise",
                    ),
                ),
            ],
            options={
                "verbose_name": "workout set",
                "verbose_name_plural": "workout sets",
                "ordering": ["position", "id"],
            },
        ),
    ]
