# Generated by Django 6.1 on 2026-10-08 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weights", "0003_weightsworkoutset"),
    ]

    operations = [
        migrations.AddField(
            model_name="weightsworkoutset",
            name="weight",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Weight used for this set, in the units from your profile.",
                max_digits=6,
                null=True,
                verbose_name="weight",
            ),
        ),
    ]
