# Generated by Django 6.1 on 2026-10-08 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weights", "0004_weightsworkoutset_weight"),
    ]

    operations = [
        migrations.AddField(
            model_name="weightsworkoutset",
            name="duration_seconds",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="For timed exercises, how long the set lasted.",
                null=True,
                verbose_name="duration (seconds)",
            ),
        ),
    ]
