# Generated by Django 6.1 on 2026-10-08 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weights", "0005_weightsworkoutset_duration_seconds"),
    ]

    operations = [
        migrations.AddField(
            model_name="weightsworkoutset",
            name="rest_seconds",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Optional rest taken after this set.",
                null=True,
                verbose_name="rest (seconds)",
            ),
        ),
    ]
