# Generated by Django 6.1 on 2026-10-08 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weights", "0006_weightsworkoutset_rest_seconds"),
    ]

    operations = [
        migrations.CreateModel(
            name="WeightsWorkoutSuperset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "letter",
                    models.CharField(
                        help_text="Label for the superset, e.g. A.",
                        max_length=1,
                        verbose_name="letter",
                    ),
                ),
                (
                    "rest_seconds",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Rest taken at the end of each round of the superset.",
                        null=True,
                        verbose_name="rest (seconds)",
                    ),
                ),
                (
                    "workout",
                    models.ForeignKey(
                        help_text="The workout this superset belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supersets",
                        to="weights.weightsworkout",
                        verbose_name="workout",
                    ),
                ),
            ],
            options={
                "verbose_name": "superset",
                "verbose_name_plural": "supersets",
                "ordering": ["letter"],
            },
        ),
        migrations.AddField(
            model_name="weightsworkoutexercise",
            name="superset",
            field=models.ForeignKey(
                blank=True,
                help_text="The superset this exercise belongs to, if any.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="exercises",
                to="weights.weightsworkoutsuperset",
                verbose_name="superset",
            ),
        ),
        migrations.AddConstraint(
            model_name="weightsworkoutsuperset",
            constraint=models.UniqueConstraint(
                fields=("workout", "letter"), name="unique_superset_letter"
            ),
        ),
    ]
