# Generated by Django 6.1 on 2026-10-08 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weights", "0007_weightsworkoutsuperset_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="weightsworkout",
            name="plan",
            field=models.ForeignKey(
                blank=True,
                help_text="The planned workout this one was started from.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sessions",
                to="weights.weightsworkout",
                verbose_name="plan",
            ),
        ),
        migrations.AddField(
            model_name="weightsworkoutset",
            name="completed",
            field=models.BooleanField(
                default=False,
                help_text="Whether this set has been done.",
                verbose_name="done",
            ),
        ),
    ]
