# Generated by Django 6.1 on 2026-10-08 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weights", "0008_weightsworkout_plan_weightsworkoutset_completed"),
    ]

    operations = [
        migrations.AddField(
            model_name="weightsworkout",
            name="is_actual",
            field=models.BooleanField(
                default=False,
                help_text="Whether this workout has been done, rather than planned.",
                verbose_name="actual",
            ),
        ),
    ]
