# Generated by Django 6.1 on 2026-10-08 00:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Health",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Weight in pounds.",
                        max_digits=5,
                        null=True,
                        verbose_name="weight (lb)",
                    ),
                ),
                (
                    "systolic",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Systolic blood pressure in mmHg.",
                        null=True,
                        verbose_name="systolic blood pressure",
                    ),
                ),
                (
                    "diastolic",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Diastolic blood pressure in mmHg.",
                        null=True,
                        verbose_name="diastolic blood pressure",
                    ),
                ),
                (
                    "resting_heart_rate",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Resting heart rate in beats per minute.",
                        null=True,
                        verbose_name="resting heart rate",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The user who recorded these measurements.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="health_records",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
            ],
            options={
                "verbose_name": "health",
                "verbose_name_plural": "health",
                "ordering": ["-created_at"],
            },
        ),
    ]
